### ISSUE TITLE
Crash when crossing dimensions

### ISSUE THREAD

**Issue by bryanjblake** [mrAppleXZ/LargeStuff#1]
[crash-2016-07-10_18.04.37-server.txt](https://github.com/mrAppleXZ/LargeStuff/files/356220/crash-2016-07-10_18.04.37-server.txt)

**Comment by mrapplexz** [comment]
Confirmed, I'm working on a fix for this bug.

**Comment by mrapplexz** [comment]
Fixed in 2.1.2 build.
